# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 20:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_auto_20161217_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izposojeno',
            name='izposoja',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='izposojeno',
            name='vracilo',
            field=models.BooleanField(default=False),
        ),
    ]
