# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokacija',
            name='nadstropje',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lokacija',
            name='omara',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lokacija',
            name='polica',
            field=models.IntegerField(),
        ),
    ]
